#!/usr/bin/php
<?php
	chdir(dirname($argv[0]));
	require("../libraries/banshee.php");
	require("../libraries/security.php");

	$db = new MySQLi_connection(DB_HOSTNAME, DB_DATABASE, DB_USERNAME, DB_PASSWORD);
	if ($db->connected == false) {
		exit("Internal error: database not available.\n");
	}

	if (count($argv) <= 1) {
		exit("Usage: ".$argv[0]." <username>\n");
	}
	$username = $argv[1];

	$query = "select * from users where username=%s";
	if (($result = $db->execute($query, $username)) === false) {
		exit("Error while checking username.\n");
	}
	if (count($result) == 0) {
		exit("User ".$username." not found.\n");
	}
	$user = $result[0];

	do {
		print "Enter password: ";
		system("/bin/stty -echo");
		$password = trim(fgets(STDIN));
		system("/bin/stty echo");
		print "\n";
	} while ($password == "");

	$hashed = hash(PASSWORD_HASH, $password.hash(PASSWORD_HASH, $username));
	if ($hashed != $user["password"]) {
		exit("Invalid password.\n");
	}
	$password = hash_password($password, $username);

	$query = "update users set password=%s where username=%s";
	if ($db->query($query, $password, $username) === false) {
		exit("Database error while changing password.\n");
	}
?>
